# Generated by Django 5.0 on 2024-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='delete_status',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'ORDER_PROCESSED'), (3, 'ORDER_DELIVERED'), (4, 'ORDER_REJECTED')], default=0),
        ),
    ]
